# Generated by Django 3.2.8 on 2021-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaveapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=12)),
                ('startingdate', models.TextField(max_length=12)),
                ('endingdate', models.TextField(max_length=12)),
                ('reason', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Leaveapprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(default='', max_length=15, null=True)),
                ('name', models.TextField(max_length=12)),
                ('startingdate', models.TextField(max_length=12)),
                ('endingdate', models.TextField(max_length=12)),
                ('reason', models.TextField(max_length=12)),
                ('status', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Leavedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(default='', max_length=15, null=True)),
                ('name', models.TextField(max_length=12)),
                ('startingdate', models.TextField(max_length=12)),
                ('endingdate', models.TextField(max_length=12)),
                ('reason', models.TextField(max_length=12)),
                ('status', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Leavereject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(default='', max_length=15, null=True)),
                ('name', models.TextField(max_length=12)),
                ('startingdate', models.TextField(max_length=12)),
                ('endingdate', models.TextField(max_length=12)),
                ('reason', models.TextField(max_length=12)),
                ('status', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=12)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=12)),
                ('bank', models.TextField(max_length=12)),
                ('branch', models.TextField(max_length=12)),
                ('base', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(max_length=12)),
                ('lastname', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=12)),
                ('task', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Taskassign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=12)),
                ('task', models.TextField(max_length=12)),
            ],
        ),
    ]
